# Copyright (C) 2014  Jim Turner
#
# This program is free software: you can redistribute it and/or modify
# it under the terms of the GNU General Public License as published by
# the Free Software Foundation, either version 2 of the License, or
# (at your option) any later version.
#
# This program is distributed in the hope that it will be useful,
# but WITHOUT ANY WARRANTY; without even the implied warranty of
# MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
# GNU General Public License for more details.
#
# You should have received a copy of the GNU General Public License
# along with this program.  If not, see <http://www.gnu.org/licenses/>.

latex:
  replacements:
    - ['&', '\&']
    - ['%', '\%']
    - ['\$', '\$']
    - ['LaTeX', '\LaTeX']
    - ['//(.*?)//', '\emph{\1}']
  jinja2_delim: ['%<', '>%', '<<', '>>', '%%<', '>%%']
  line_endings: "\n"
html:
  replacements:
    - ['&', '&amp;']
    - ['---', '&mdash;']
    - ['--', '&ndash;']
    - ['``', '&ldquo;']
    - ["''", '&rdquo;']
    - ["'", '&rsquo;']
    - ['~', '&nbsp;']
    - ['LaTeX', 'L<span style="text-transform: uppercase; font-size: 70%; margin-left: -0.36em; vertical-align: 0.3em; line-height: 0; margin-right: -0.15em">a</span>T<span style="text-transform: uppercase; margin-left: -0.1667em; vertical-align: -0.5ex; line-height: 0; margin-right: -0.125em">e</span>X']
    - ['//(.*?)//', '<em>\1</em>']
  jinja2_delim: ['{%', '%}', '{{', '}}', '{#', '#}']
  line_endings: "\n"
txt:
  replacements:
    - ['---', '—']
    - ['--', '–']
    - ['``', '“']
    - ["''", '”']
    - ["'", '’']
    - ['~', ' ']
    - ['//(.*?)//', '\1']
  jinja2_delim: ['{%', '%}', '{{', '}}', '{#', '#}']
  line_endings: "\r\n"
rst:
  replacements:
    - ['---', '—']
    - ['--', '–']
    - ['``', '“']
    - ["''", '”']
    - ["'", '’']
    - ['~', ' ']
    - ['//(.*?)//', '\1']
  jinja2_delim: ['{%', '%}', '{{', '}}', '{#', '#}']
  line_endings: "\n"
